# Generated by Django 3.1.2 on 2020-10-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_auto_20201022_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('area_of_expertees', models.CharField(choices=[('actingteacher', 'actingteacher'), ('2', 'videoediting'), ('3', 'audioediting'), ('4', 'direction'), ('5', 'acting'), ('6', 'musician'), ('7', 'teator acting'), ('8', 'vfx'), ('9', 'technician'), ('10', 'others')], default='new', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('tell_us_about_yourself', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mainman',
            name='area_of_expertees',
            field=models.CharField(choices=[('actingteacher', 'actingteacher'), ('2', 'videoediting'), ('3', 'audioediting'), ('4', 'direction'), ('5', 'acting'), ('6', 'musician'), ('7', 'teator acting'), ('8', 'vfx'), ('9', 'technician'), ('10', 'others')], default='new', max_length=100),
        ),
    ]
