# Generated by Django 3.1.2 on 2020-10-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0003_auto_20201026_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='area_of_expertees',
            field=models.CharField(choices=[('acting teacher', 'acting teacher'), ('video editing', 'video editing'), ('audio editing', 'audio editing'), ('direction', 'direction'), ('acting', 'acting'), ('musician', 'musician'), ('theator acting', 'theator acting'), ('vfx', 'vfx'), ('technician', 'technician'), ('others', 'others')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainman',
            name='area_of_expertees',
            field=models.CharField(choices=[('acting teacher', 'acting teacher'), ('video editing', 'video editing'), ('audio editing', 'audio editing'), ('direction', 'direction'), ('acting', 'acting'), ('musician', 'musician'), ('theator acting', 'theator acting'), ('vfx', 'vfx'), ('technician', 'technician'), ('others', 'others')], default='new', max_length=100),
        ),
    ]
