# Generated by Django 3.1.2 on 2020-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0004_auto_20201026_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='area_of_expertees',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='date',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='email',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='tell_us_about_yourself',
        ),
        migrations.AddField(
            model_name='camera',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='camera',
            name='subject',
            field=models.TextField(blank=True, default='fill', null=True),
        ),
    ]
