# Generated by Django 3.1.2 on 2020-10-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0005_auto_20201029_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='subject',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
