# Generated by Django 3.1.2 on 2020-10-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0009_auto_20201029_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=0, default='', max_digits=10)),
                ('subject', models.TextField(blank=True, default='', null=True)),
                ('type', models.CharField(choices=[('portable field mixer', 'portable field mixer'), ('field recorder', 'field recorder'), ('Wireless microphone systems', 'Wireless microphone systems'), ('shotgun microphones', 'shotgun microphones'), ('Wind protection for the mics', 'Wind protection for the mics')], default='new', max_length=100)),
            ],
        ),
    ]
