# Generated by Django 3.1.2 on 2020-10-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0011_auto_20201029_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('portable field mixer', 'portable field mixer'), ('field recorder', 'field recorder'), ('Wireless microphone systems', 'Wireless microphone systems'), ('shotgun microphones', 'shotgun microphones'), ('Wind protection for the mics', 'Wind protection for the mics'), ('boompole', 'boompole'), ('Headphones', 'Headphones')], default='new', max_length=100),
        ),
    ]
