# Generated by Django 3.1.2 on 2020-10-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0012_auto_20201030_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
