# Generated by Django 3.1.2 on 2020-10-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0014_auto_20201030_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainman',
            name='subject',
        ),
        migrations.AlterField(
            model_name='mainman',
            name='area_of_expertees',
            field=models.CharField(choices=[('acting teacher', 'acting teacher'), ('video editing', 'video editing'), ('audio editing', 'audio editing'), ('direction', 'direction'), ('acting', 'acting'), ('musician', 'musician'), ('theator acting', 'theator acting'), ('vfx', 'vfx'), ('technician', 'technician'), ('others', 'others')], default='------', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainman',
            name='email',
            field=models.EmailField(blank=True, default='------', max_length=254),
        ),
        migrations.AlterField(
            model_name='mainman',
            name='name',
            field=models.CharField(default='------', max_length=30),
        ),
        migrations.AlterField(
            model_name='mainman',
            name='tell_us_about_yourself',
            field=models.TextField(blank=True, default='------', null=True),
        ),
    ]
