# Generated by Django 3.1.2 on 2020-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0016_auto_20201030_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='audioe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softwarename', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='mainman',
            name='area_of_expertees',
            field=models.CharField(choices=[('', ''), ('acting teacher', 'acting teacher'), ('video editing', 'video editing'), ('audio editing', 'audio editing'), ('direction', 'direction'), ('acting', 'acting'), ('musician', 'musician'), ('theator acting', 'theator acting'), ('vfx', 'vfx'), ('technician', 'technician'), ('others', 'others')], default='', max_length=100),
        ),
    ]
