# Generated by Django 3.1.2 on 2020-10-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0017_auto_20201031_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softwarename', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
