# Generated by Django 3.1.3 on 2020-12-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0022_sw'),
    ]

    operations = [
        migrations.CreateModel(
            name='resumeupload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
