# Generated by Django 3.1.3 on 2020-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0024_auto_20201203_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.AddField(
            model_name='mainman',
            name='file',
            field=models.FileField(default='', upload_to='resumes'),
        ),
    ]
